name: 'build_push_docker'

description: 'Builds and pushes Docker images (one per branch in the corresponding directory)'

on:
  push:
    branches-ignore:
      # Runs for all branches except the main branch
      - 'main'

# ${github.ref_name}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${github.ref_name}
          push: true
          tags: 'gabrieleara/dev_environment:${github.ref_name}'
