name: Build and Push on DockerHub

on:
  # This workflow euns for all branches except the main branch

  # Run workflow on push of a new commit
  push:
    branches-ignore:
      - main

  # Run workflow when the 'Manually Run a Workflow' is triggered
  workflow_run:
    workflows: ['Manually Run a Workflow']
    types:
      - completed
    branches-ignore:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: '${{ github.ref_name }}'
          push: true
          tags: 'gabrieleara/dev_environment:${{ github.ref_name }}'
