name: Build and Push on DockerHub

on:
  # This workflow runs for all branches except the main
  # branch or dependabot-created ones

  # Run workflow on push of a new commit
  push:
    branches-ignore:
      - main
      - 'dependabot/**'
  workflow_dispatch:
    branches-ignore:
      - main
      - 'dependabot/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: '${{ github.ref_name }}'
          push: true
          tags: 'gabrieleara/dev_environment:${{ github.ref_name }}'
